name: Build and push Docker images

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip Upstream Source Code
        run: |
          curl -OL https://github.com/lsky-org/lsky-pro/archive/refs/heads/master.zip
          unzip *.zip
          mv lsky-pro-master/* ../
	  mv lsky-pro-master/.env.example ../
          rm -rf lsky-pro-master

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: halcyonazure/lsky-pro-docker:latest
